# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Corney
email: dpacorney@gmail.com
description: "A blog about natural language processing, machine learning, fact checking. My opinions about GPT3, generative AI. 
My work at Full Fact, part of the International Fact Checking Network."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dcorney.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dcorney
github_username:  dcorney

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages','.well-known']
markdown: kramdown
# markdown was kramdown
theme: minima
kramdown:
  input: GFM
future: true
  
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock